services:
  computer_vision_app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: computer-vision
    container_name: computer-vision
    command: sleep infinity
    working_dir: /app
    volumes:
      # Mount folder computer-vision ke /app
      - ../:/app:Z
    ports:
      # Port untuk backend
      - "8080:8080"
    env_file:
      - ../.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
